name: docker-publish
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true

jobs:
  publish:
    name: docker-publish
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: "docker build -t subsquid/substrate-gateway:${{ github.event.inputs.tag }} ."

      - name: Publish
        run: "docker push subsquid/substrate-gateway:${{ github.event.inputs.tag }}"
